trusting $PATH

diff --git a/pwdshow b/pwdshow
--- a/pwdshow
+++ b/pwdshow
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-pwshome=$(/usr/bin/dirname $(/bin/readlink -f "$0"))
+pwshome=$(dirname $(readlink -f "$0"))
 
 . "$pwshome/pwdcnf"
 
@@ -8,8 +8,8 @@ pws_path "$1"
 
 if [ -f "$pws_path" ]
 then
-  $gpg_bin --no-verbose -q -d "$pws_path"
+  gpg --no-verbose -q -d "$pws_path"
 else
-  echo "error: $1 not found" >&2
+  echo "error: "$1" not found" >&2
   exit 1
 fi
